### ISSUE TITLE
hair parts aren't following the rig

### ISSUE THREAD

**Issue by saaciujsdh** [nanoskript/vrm-rigify#11]
after the parenting part, i tested it by moving the waist part of the rig. The model is moving fine but for some reason, the extra parts of the hair did not move 
![image_2023-12-22_224325564](https://github.com/nanoskript/vrm-rigify/assets/154611698/e3628ea8-210e-4e80-95d1-c60ac2beff95)

**Comment by Cappyadams** [comment]
That's because when you generate the rig, The hair bones are ignored and stay in the original rig.
You have to separate the hair bones from the original rig, join the hair and rigify rigs, and parent the hair bones to the head.
(Hope I explained it well. I can show you the fix to this though a video if you're confused)

**Comment by Pawana93** [comment]
I would appreciate a video ... that would be really helpful :)

> That's because when you generate the rig, The hair bones are ignored and stay in the original rig. You have to separate the hair bones from the original rig, join the hair and rigify rigs, and parent the hair bones to the head. (Hope I explained it well. I can show you the fix to this though a video if you're confused)

**Comment by Cappyadams** [comment]
> I would appreciate a video ... that would be really helpful :)
> 
> > That's because when you generate the rig, The hair bones are ignored and stay in the original rig. You have to separate the hair bones from the original rig, join the hair and rigify rigs, and parent the hair bones to the head. (Hope I explained it well. I can show you the fix to this though a video if you're confused)

Due to github being dumb, I had to upload the video to MEGA. I hope the vid helped! <3
https://mega.nz/file/y2ZSiIZQ#ouCggjDDX-3kCecZJO28NKxqv5rm4m5Rbqs6KovcWIg

**Comment by nanoskript** [comment]
Hello! Apologies for the late reply. This issue occurs when the armature modifier for the meshes is after the `MToon` shaders, and not before. Please see **Step 5** in the README under **Parenting the meshes to the armature**. 

I'm closing this issue for now. Feel free to reopen if this doesn't work!
