### ISSUE TITLE
hand bone not generating

### ISSUE THREAD

**Issue by Mqtteo0** [nanoskript/vrm-rigify#3]
Like the title says, the hand ik bone is not generating for some reason, there are no errors or anything, its just isnt there.
The rest of the rig works well.

**Comment by nanoskript** [comment]
Could you elaborate on what you mean? It seems like the hand bone is being generated from my testing:

<img width="567" alt="image" src="https://github.com/nanoskript/vrm-rigify/assets/96655713/c2dfc4cd-d496-407b-b15f-33edad956d81">

If you have a particular model file causing this issue, that'd be helpful as well.

**Comment by Mqtteo0** [comment]
> Hi, could you elaborate on what you mean? It seems like the hand bone is being generated from my testing:
> 
> <img alt="image" width="567" src="https://user-images.githubusercontent.com/96655713/237961472-c2dfc4cd-d496-407b-b15f-33edad956d81.png">
> If you have a particular model file causing this issue, that'd be helpful as well.

im so dumb omg, the bone was so small that i didnt saw it, it works yeah haha, anyway thanks for the reply
