### ISSUE TITLE
Can generation for hair be added?

### ISSUE THREAD

**Issue by azur1s** [nanoskript/vrm-rigify#4]
As of right now after my model after the humanized step it's all correct except that there's no hair bones. I am trying to manually move the old hair bones to the new armature but I don't really know how. Could it be generated along side when doing the humanized step?

I'm trying both just parenting and joining both armatures, but the hair bones does not move with the head's rotation and I don't really know how to get it to work together.

Sorry if it does not sound clear, I don't really know how to explain it. :P

**Comment by nanoskript** [comment]
The hair bones should already be copied over to the new armature. Not all the bone layers are visible by default so you will need to enter Pose Mode and select the Armature, and then in Object Data Properties, enable the layer for the hair bones (and other miscellaneous bones):

<img width="329" alt="image" src="https://github.com/nanoskript/vrm-rigify/assets/96655713/e8e4a840-4830-4019-abfc-3ba67e111ebb">

This is what it looks like in the viewport with just the layer with the hair bones enabled:

<img width="704" alt="image" src="https://github.com/nanoskript/vrm-rigify/assets/96655713/2581ea82-0855-4d2a-afcd-581adc164df9">

**Comment by azur1s** [comment]
Thanks! I havent noticed it all along 😅. So this issue could probably be closed?

**Comment by nanoskript** [comment]
Feel free to close the issue if you feel that your question has been answered.

**Comment by azur1s** [comment]
Thanks a lot!
