### ISSUE TITLE
in Pose Mode, mash did not move, only the rig moved.

### ISSUE THREAD

**Issue by supwang** [nanoskript/vrm-rigify#6]
How to slove below problem?
<img width="626" alt="Screenshot 2023-07-15 211402" src="https://github.com/nanoskript/vrm-rigify/assets/4122964/7956bb0b-0a85-4f88-8b1c-1d60a0bd8fce">
<img width="386" alt="Screenshot 2023-07-15 211834" src="https://github.com/nanoskript/vrm-rigify/assets/4122964/e9dfa72d-130c-47f4-8308-2d3abc7ba7fc">

Thank you.

**Comment by nanoskript** [comment]
Did you follow the steps under: "Parenting the meshes to the armature"?

**Comment by supwang** [comment]
> Did you follow the steps under: "Parenting the meshes to the armature"?

Thank you for you reply.
Yes, I followed the steps under: "Parenting the meshes to the armature".

**Comment by supwang** [comment]
> Did you follow the steps under: "Parenting the meshes to the armature"?

Is the operation correct? (I'm using Blender 3.5)
<img width="1540" alt="Screenshot 2023-07-15 230328" src="https://github.com/nanoskript/vrm-rigify/assets/4122964/605dbe5b-f0cd-43f8-8005-e9197d064d6a">

**Comment by nanoskript** [comment]
That appears to be correct. It would be easiest for me to investigate if you could attach a copy of your VRM model (or another model that exhibits the same problem). Otherwise, I'm not sure what the issue is.

The only other reason I can think of is that you might using a VRM 1.0 instead of a VRM 0.x model.

**Comment by supwang** [comment]
> That appears to be correct. It would be easiest for me to investigate if you could attach a copy of your VRM model (or another model that exhibits the same problem). Otherwise, I'm not sure what the issue is.
> 
> The only other reason I can think of is that you might using a VRM 1.0 instead of a VRM 0.x model.

I’m using VRoid's sample avatars that downloaded from VRoid Hub.

**Comment by nanoskript** [comment]
I can't reproduce the problem.

Here's what I did:
1. I downloaded the sample avatar from: https://hub.vroid.com/en/characters/2843975675147313744/models/5644550979324015604
2. I imported the model into Blender.
3. I applied the "Generate Humanized VRM Rig" command.
4. I parented the meshes inside `Armature` to the `Armature.rig` rig.
5. I entered "Pose Mode" on `Armature.rig`.

<img width="648" alt="image" src="https://github.com/nanoskript/vrm-rigify/assets/96655713/93eb0c84-7faf-47c6-81f2-fabe56abe163">

The outline should look like this:
<img width="312" alt="image" src="https://github.com/nanoskript/vrm-rigify/assets/96655713/f82a38a8-9c2c-42dc-8202-1909cf17261f">

**Comment by supwang** [comment]
> I can't reproduce the problem.
> 
> Here's what I did:
> 
> 1. I downloaded the sample avatar from: https://hub.vroid.com/en/characters/2843975675147313744/models/5644550979324015604
> 2. I imported the model into Blender.
> 3. I applied the "Generate Humanized VRM Rig" command.
> 4. I parented the meshes inside `Armature` to the `Armature.rig` rig.
> 5. I entered "Pose Mode" on `Armature.rig`.

Thank you.

**Comment by supwang** [comment]
It seems have no bones in the Armature.rig?
<img width="1166" alt="Screenshot 2023-07-17 223428" src="https://github.com/nanoskript/vrm-rigify/assets/4122964/3ac13f94-4f3c-4a78-a578-e77ac6c0a2eb">

**Comment by nanoskript** [comment]
Not all bone layers are shown by default, see this comment: https://github.com/nanoskript/vrm-rigify/issues/4#issuecomment-1555863317.

**Comment by supwang** [comment]
> Not all bone layers are shown by default, see this comment: [#4 (comment)](https://github.com/nanoskript/vrm-rigify/issues/4#issuecomment-1555863317). This is something that Rigify does and is unrelated to VRM-Rigify.

Thank you, I think that I can not run the add-ons successfully.
