### ISSUE TITLE
Rigify armature generation crashes on Blender 3.0 & 3.6

### ISSUE THREAD

**Issue by viitana** [nanoskript/vrm-rigify#8]
Hi, it seems that the plugin is crashing when generating the Rigify armature / Humanized VRM Rig on fresh Blender 3.0 and 3.6 installs in Windows with a VRM from VRoid Studio.

Upon importing a fresh VRM file exported from Vroid Studio 0.14.0, selecting the armature and doing `Generate Humanized VRM Rig`, I get the following error on both Blender versions:

```python
Python: Traceback (most recent call last):
  File "C:\Users\SomeUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\vrm_rigify\__init__.py", line 42, in execute
    meta_rig = meta.generate_meta_rig(vroid_rig)
  File "C:\Users\SomeUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\vrm_rigify\meta.py", line 69, in generate_meta_rig
    bpy.ops.object.armature_human_metarig_add()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.object.armature_human_metarig_add" error, could not be found
```

Blender version: 3.0.1 / 3.6.3
vrm-rigify version: latest build (Aug 20, 2023)
[VRM-Addon-for-Blender](https://github.com/saturday06/VRM-Addon-for-Blender) version:  2.20.7
Vroid Studio version: 0.14.0

What's the supported Blender version for this plugin? I could not find any info.

**Comment by viitana** [comment]
Turns out this was simply a case of forgetting to enable the Rigify addon. Plugin work fine now with Rigify enabled, sorry for the false alarm!

Could be useful to run some kind of check that Rigify is present and issue a more descriptive warning if not. This `armature_human_metarig_add` function in the error stack was pretty badly documented, leading me to take a while to realize what the underlying issue was.

**Comment by nanoskript** [comment]
Fixed in https://github.com/nanoskript/vrm-rigify/commit/cd00b1f12e8c39461eaf293ccb33f52114aa9087. 👍
